// Validates src/browser/relay/wire.ts against the shared cross-language
// vectors vendored from the relay repo (test/vectors/, generated by
// `go run ./cmd/genvectors` — see that repo's spec/PROTOCOL.md). The Go
// and Rust implementations are checked against the exact same files. If
// this fails after editing wire.ts, either the code has a bug or the
// vectors are stale and need regenerating + re-vendoring; if it fails
// after only touching this file, this file has a bug.
import { describe, expect, it } from 'vitest'
import {
  WireError,
  decodeInnerAll,
  encodeInner,
  encodeOuter,
  isClientInitiated,
  parseOuter,
  type InnerFrame
} from '@browser/relay/wire'

import frameOuterVectors from '../vectors/frame_outer.json'
import frameInnerVectors from '../vectors/frame_inner.json'

function hexDecode(s: string): Uint8Array {
  if (s.length === 0) return new Uint8Array(0)
  const bytes = new Uint8Array(s.length / 2)
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(s.slice(i * 2, i * 2 + 2), 16)
  }
  return bytes
}

function hexEncode(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')
}

interface FrameOuterEncodeCase {
  name: string
  channel_hex: string
  payload_hex: string
  want_hex: string
}
interface FrameOuterParseCase {
  name: string
  raw_hex: string
  want_channel_hex?: string
  want_payload_hex?: string
  expect_error?: string
}

describe('wire vectors: frame_outer', () => {
  const vectors = frameOuterVectors as {
    encode: FrameOuterEncodeCase[]
    parse: FrameOuterParseCase[]
  }

  it.each(vectors.encode)('encode/$name', (c: FrameOuterEncodeCase) => {
    const channel = hexDecode(c.channel_hex)[0]
    const got = encodeOuter(channel, hexDecode(c.payload_hex))
    expect(hexEncode(got)).toBe(c.want_hex)
  })

  it.each(vectors.parse)('parse/$name', (c: FrameOuterParseCase) => {
    if (c.expect_error) {
      let caught: unknown
      try {
        parseOuter(hexDecode(c.raw_hex))
      } catch (e) {
        caught = e
      }
      expect(caught).toBeInstanceOf(WireError)
      expect((caught as WireError).code).toBe(c.expect_error)
      return
    }
    const { header, payload } = parseOuter(hexDecode(c.raw_hex))
    expect(hexEncode(new Uint8Array([header.channel]))).toBe(c.want_channel_hex)
    expect(hexEncode(payload)).toBe(c.want_payload_hex)
  })
})

interface FrameInnerEncodeCase {
  name: string
  type_hex: string
  stream_id: number
  payload_hex?: string
  want_hex?: string
  expect_error?: string
}
interface FrameInnerWantFrame {
  type_hex: string
  stream_id: number
  payload_hex?: string
}
interface FrameInnerDecodeCase {
  name: string
  buf_hex: string
  want_frames?: FrameInnerWantFrame[]
  expect_error?: string
}

describe('wire vectors: frame_inner', () => {
  const vectors = frameInnerVectors as {
    encode: FrameInnerEncodeCase[]
    decode: FrameInnerDecodeCase[]
  }

  it.each(vectors.encode)('encode/$name', (c: FrameInnerEncodeCase) => {
    const frame: InnerFrame = {
      type: hexDecode(c.type_hex)[0],
      streamId: c.stream_id,
      payload: hexDecode(c.payload_hex ?? '')
    }
    if (c.expect_error) {
      let caught: unknown
      try {
        encodeInner(frame)
      } catch (e) {
        caught = e
      }
      expect(caught).toBeInstanceOf(WireError)
      expect((caught as WireError).code).toBe(c.expect_error)
      return
    }
    expect(hexEncode(encodeInner(frame))).toBe(c.want_hex)
  })

  it.each(vectors.decode)('decode/$name', (c: FrameInnerDecodeCase) => {
    if (c.expect_error) {
      let caught: unknown
      try {
        decodeInnerAll(hexDecode(c.buf_hex))
      } catch (e) {
        caught = e
      }
      expect(caught).toBeInstanceOf(WireError)
      expect((caught as WireError).code).toBe(c.expect_error)
      return
    }
    const frames = decodeInnerAll(hexDecode(c.buf_hex))
    const want = c.want_frames ?? []
    expect(frames).toHaveLength(want.length)
    frames.forEach((got, i) => {
      expect(hexEncode(new Uint8Array([got.type]))).toBe(want[i].type_hex)
      expect(got.streamId).toBe(want[i].stream_id)
      expect(hexEncode(got.payload)).toBe(want[i].payload_hex ?? '')
    })
  })
})

describe('wire: hand-written round-trip checks', () => {
  it('encodes and decodes a single frame', () => {
    const frame: InnerFrame = { type: 0x01, streamId: 1, payload: new TextEncoder().encode('hello') }
    const buf = encodeInner(frame)
    const frames = decodeInnerAll(buf)
    expect(frames).toHaveLength(1)
    expect(frames[0].type).toBe(0x01)
    expect(frames[0].streamId).toBe(1)
    expect(new TextDecoder().decode(frames[0].payload)).toBe('hello')
  })

  it('rejects reserved inner types on encode and decode', () => {
    for (const type of [0x09, 0x0a, 0x0b]) {
      expect(() => encodeInner({ type, streamId: 1, payload: new Uint8Array() })).toThrow(WireError)

      const raw = new Uint8Array(8)
      raw[0] = type
      expect(() => decodeInnerAll(raw)).toThrow(WireError)
    }
  })

  it('rejects reserved outer flag bits', () => {
    for (let bit = 1; bit < 8; bit++) {
      const msg = new Uint8Array([0x00, 1 << bit, 0xaa])
      expect(() => parseOuter(msg)).toThrow(WireError)
    }
  })

  it('rejects conn_id present in v1', () => {
    const msg = new Uint8Array([0x01, 0x01, 1, 2, 3, 4, 5, 6, 7, 8, 0xaa])
    let caught: unknown
    try {
      parseOuter(msg)
    } catch (e) {
      caught = e
    }
    expect(caught).toBeInstanceOf(WireError)
    expect((caught as WireError).code).toBe('conn_id_not_v1')
  })

  it('identifies client-initiated (odd) stream ids', () => {
    expect(isClientInitiated(1)).toBe(true)
    expect(isClientInitiated(3)).toBe(true)
    expect(isClientInitiated(0)).toBe(false)
    expect(isClientInitiated(2)).toBe(false)
  })
})
